class Prime:
    def __init__(self) ->  None: ...
    def DetectPrime(self, number:int)-> bool: ...
    def RangePrimes(self, start:int,stop:int) -> list:...

_inst = Prime()
DetectPrime = _inst.DetectPrime
RangePrimes = _inst.RangePrimes